[2023-11-22T05:39:01.184+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-22T05:38:56.423824+00:00/task_id=step2 permission to 509
[2023-11-22T05:39:01.214+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-22T05:38:56.423824+00:00/task_id=step2 permission to 509
[2023-11-22T05:39:01.244+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.step2 manual__2023-11-22T05:38:56.423824+00:00 [queued]>
[2023-11-22T05:39:01.253+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.step2 manual__2023-11-22T05:38:56.423824+00:00 [queued]>
[2023-11-22T05:39:01.254+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T05:39:01.268+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): step2> on 2023-11-22 05:38:56.423824+00:00
[2023-11-22T05:39:01.273+0000] {standard_task_runner.py:57} INFO - Started process 1580 to run task
[2023-11-22T05:39:01.276+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'step2', 'manual__2023-11-22T05:38:56.423824+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpij51jase']
[2023-11-22T05:39:01.277+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask step2
[2023-11-22T05:39:01.322+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-22T05:38:56.423824+00:00/task_id=step2 permission to 509
[2023-11-22T05:39:01.325+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.step2 manual__2023-11-22T05:38:56.423824+00:00 [running]> on host 50f4a498a395
[2023-11-22T05:39:01.397+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='step2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T05:38:56.423824+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T05:38:56.423824+00:00'
[2023-11-22T05:39:01.398+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-22T05:39:01.399+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'ls /opt/***/data/2023-11-22/downloads']
[2023-11-22T05:39:01.408+0000] {subprocess.py:86} INFO - Output:
[2023-11-22T05:39:01.419+0000] {subprocess.py:93} INFO - ls: cannot access '/opt/***/data/2023-11-22/downloads': No such file or directory
[2023-11-22T05:39:01.420+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-22T05:39:01.430+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-22T05:39:01.435+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=step2, execution_date=20231122T053856, start_date=20231122T053901, end_date=20231122T053901
[2023-11-22T05:39:01.448+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task step2 (Bash command failed. The command returned a non-zero exit code 2.; 1580)
[2023-11-22T05:39:01.489+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T05:39:01.526+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
