[2023-11-22T05:39:10.268+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-22T05:39:06.823713+00:00/task_id=step2 permission to 509
[2023-11-22T05:39:10.298+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-22T05:39:06.823713+00:00/task_id=step2 permission to 509
[2023-11-22T05:39:10.334+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.step2 manual__2023-11-22T05:39:06.823713+00:00 [queued]>
[2023-11-22T05:39:10.343+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.step2 manual__2023-11-22T05:39:06.823713+00:00 [queued]>
[2023-11-22T05:39:10.344+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T05:39:10.357+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): step2> on 2023-11-22 05:39:06.823713+00:00
[2023-11-22T05:39:10.362+0000] {standard_task_runner.py:57} INFO - Started process 1587 to run task
[2023-11-22T05:39:10.365+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'step2', 'manual__2023-11-22T05:39:06.823713+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmptmrh097i']
[2023-11-22T05:39:10.366+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask step2
[2023-11-22T05:39:10.411+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-22T05:39:06.823713+00:00/task_id=step2 permission to 509
[2023-11-22T05:39:10.414+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.step2 manual__2023-11-22T05:39:06.823713+00:00 [running]> on host 50f4a498a395
[2023-11-22T05:39:10.497+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='step2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T05:39:06.823713+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T05:39:06.823713+00:00'
[2023-11-22T05:39:10.498+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-22T05:39:10.500+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'ls /opt/***/data/2023-11-22/downloads']
[2023-11-22T05:39:10.512+0000] {subprocess.py:86} INFO - Output:
[2023-11-22T05:39:10.517+0000] {subprocess.py:93} INFO - ls: cannot access '/opt/***/data/2023-11-22/downloads': No such file or directory
[2023-11-22T05:39:10.518+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-22T05:39:10.530+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-22T05:39:10.534+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=step2, execution_date=20231122T053906, start_date=20231122T053910, end_date=20231122T053910
[2023-11-22T05:39:10.550+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task step2 (Bash command failed. The command returned a non-zero exit code 2.; 1587)
[2023-11-22T05:39:10.578+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T05:39:10.597+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
